### ISSUE TITLE
FCGear fails to act on axis information

### ISSUE THREAD

**Issue by kcleung** [looooo/FCGear#12]
When I create an involute gear, the axis starts off as [0.0, 0.0, 1.0]

However, after I change it to something else, such as [1.0, 0.0, 0.0], FCGear fails to update the axis of the gear.

**Comment by looooo** [comment]
I think you are trying to change the axis of rotation. This is not gear-specific. It is a property of the freecad-base-object used as base for the gears. To get the gear aligned with an axis, use the rotation-axis + a value for the rotation.

**Comment by kcleung** [comment]
Thanks!  Now I know how that works!
