### ISSUE TITLE
Install instructions are wrong! Done for a macro, not a workbench.

### ISSUE THREAD

**Issue by pperrin** [looooo/FCGear#5]
Haven't used the software yet - found the built in gears  thing were too precise for 3d printing :(

But just installed it in the freecad - mod folder (with other workbenches) and it is showing up -- but the instructions here seem to be for installing a macro...

Cheers!!

**Comment by looooo** [comment]
which os?

**Comment by pperrin** [comment]
Windows.

I put the files in:-
C:\Program Files\FreeCAD 0.16\Mod\FCGear

For the workbench to show up in the drop-down in the main app.

**Comment by looooo** [comment]
thanks for reporting this. I have updated the Readme.
